apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-custom-canary
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: hello-kubernetes-custom-canary
